config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount(GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql")
  end

  post "/graphql", to: "graphql#execute"

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  mount Commontator::Engine => '/commontator'

  resources :task_trackers

  resources :candidate_products do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :candidate_roles do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :product_suites
  resources :glossaries
  resources :settings

  resources :rubric_categories, only: [:index, :update, :create, :destroy]
  resources :category_indicators, only: [:index, :update, :create, :destroy]
  resources :maturity_rubrics do
    resources :rubric_categories do
      resources :category_indicators
    end
  end

  resources :tasks, only: [:index, :update, :create, :destroy]
  resources :activities, only: [:index, :update, :create, :destroy]

  resources :playbook_pages, only: [:index, :update, :create, :destroy]
  resources :playbooks do
    get 'count', on: :collection
    post 'upload_design_images', on: :collection
    member do
      post 'convert_pages'
    end
    resources :playbook_pages do
      member do
        get 'copy_page'
        get 'edit_content'
        get 'load_design'
        post 'save_design'
        patch 'save_design'
        get 'create_pdf'
        get 'show_pdf'
      end
    end
  end

  resources :tags
  resources :use_case_steps

  resources :projects do
    get 'count', on: :collection
    get 'export_data', on: :collection
    member do
      post 'favorite_project'
      post 'unfavorite_project'
    end
  end

  get 'deploys/index'
  get 'about/learnmore'
  get 'about', to: 'about#index'

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  scope '/admin' do
    resources :users do
      get 'statistics', on: :collection
    end
  end

  devise_scope :user do
    get '/users', to: 'registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end

  root to: redirect(path: '/products')

  resources :covid, only: [:index]

  resources :candidate_organizations do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :portal_views do
    member do
      post 'select'
    end
  end

  resources :products do
    get 'count', on: :collection
    get 'export_data', on: :collection
    member do
      post 'favorite_product'
      post 'unfavorite_product'
    end
  end

  resources :building_blocks do
    get 'count', on: :collection
    get 'export_data', on: :collection
  end

  resources :sustainable_development_goals, only: [:index, :show] do
    get 'count', on: :collection
  end

  resources :sdg_targets, only: [:index, :show]

  resources :use_case_steps, only: [:new, :create, :edit, :update, :show]
  resources :use_cases do
    get 'count', on: :collection
    get 'export_data', on: :collection
    resources :use_case_steps, only: [:new, :create, :edit, :update, :show]
    member do
      post 'favorite_use_case'
      post 'unfavorite_use_case'
    end
  end

  resources :workflows do
    get 'count', on: :collection
    get 'export_data', on: :collection
  end

  resources :deploys do
    get 'show_messages'
    post 'add_ssh_user'
  end

  resources :organizations do
    get 'count', on: :collection
    get 'export_data', on: :collection
  end

  get :update_locale, controller:"application"

  # Start of external API routes
  get 'api/v1/organizations/:id', to: 'organizations#unique_search'
  get 'api/v1/organizations', to: 'organizations#simple_search'
  post 'api/v1/organizations', to: 'organizations#complex_search'

  get 'api/v1/building_blocks/:id', to: 'building_blocks#unique_search'
  get 'api/v1/building_blocks', to: 'building_blocks#simple_search'
  post 'api/v1/building_blocks', to: 'building_blocks#complex_search'

  get 'api/v1/cities/:id', to: 'cities#unique_search'
  get 'api/v1/cities', to: 'cities#simple_search'

  get 'api/v1/countries/:id', to: 'countries#unique_search'
  get 'api/v1/countries', to: 'countries#simple_search'

  get 'api/v1/products/:id', to: 'products#unique_search'
  get 'api/v1/products', to: 'products#simple_search'
  post 'api/v1/products', to: 'products#complex_search'

  get 'api/v1/projects/:id', to: 'projects#unique_search'
  get 'api/v1/projects', to: 'projects#simple_search'
  post 'api/v1/projects', to: 'projects#complex_search'

  get 'api/v1/sectors/:id', to: 'sectors#unique_search'
  get 'api/v1/sectors', to: 'sectors#simple_search'

  get 'api/v1/sdgs/:id', to: 'sustainable_development_goals#unique_search'
  get 'api/v1/sdgs', to: 'sustainable_development_goals#simple_search'

  get 'api/v1/sustainable_development_goals/:id', to: 'sustainable_development_goals#unique_search'
  get 'api/v1/sustainable_development_goals', to: 'sustainable_development_goals#simple_search'

  get 'api/v1/tags/:id', to: 'tags#unique_search'
  get 'api/v1/tags', to: 'tags#simple_search'

  get 'api/v1/use_cases/:id', to: 'use_cases#unique_search'
  get 'api/v1/use_cases', to: 'use_cases#simple_search'
  post 'api/v1/use_cases', to: 'use_cases#complex_search'

  get 'api/v1/use_cases/:id/use_case_steps/:step_id', to: 'use_case_steps#unique_search'
  get 'api/v1/use_cases/:id/use_case_steps', to: 'use_case_steps#simple_search'

  get 'api/v1/workflows/:id', to: 'workflows#unique_search'
  get 'api/v1/workflows', to: 'workflows#simple_search'
  post 'api/v1/workflows', to: 'workflows#complex_search'

  # End of external API routes

  resources :operator_services
  resources :audits, only: [:index]
  resources :stylesheets

  resources :cities, only: [:index, :show]
  resources :countries, only: [:index, :show]

  resources :locations do
    resources :organizations
  end

  resources :sectors do
    resources :organizations
    resources :use_cases
  end

  resources :contacts do
    resources :organizations
  end

  resources :tags
  resources :use_case_steps

  get '/object_counts', to: 'application#object_counts', as: :object_counts
  post '/add_filter', to: 'application#add_filter', as: :add_filter
  post '/add_filters', to: 'application#add_filters', as: :add_filters
  post '/remove_filter', to: 'application#remove_filter', as: :remove_filter
  post '/remove_all_filters', to: 'application#remove_all_filters', as: :remove_all_filters
  get '/get_filters', to: 'application#get_filters', as: :get_filters
  get '/agg_capabilities', to: 'organizations#agg_capabilities', as: :agg_capabilities
  get '/agg_services', to: 'organizations#agg_services', as: :agg_services
  get '/service_capabilities', to: 'organizations#service_capabilities', as: :service_capabilities
  get '/update_capability', to: 'organizations#update_capability', as: :update_capability
  get '/privacy', to: 'about#privacy', as: :privacy
  get '/terms', to: 'about#terms', as: :terms
  get '/healthcheck', to: 'about#healthcheck', as: :healthcheck

  post '/save_url', to: 'application#save_url', as: :save_url
  post '/remove_url', to: 'application#remove_url', as: :remove_url

  get 'export', :to => 'organizations#export'
  get 'candidate_organization_duplicates', :to => 'candidate_organizations#duplicates'
  get 'contact_duplicates', :to => 'contacts#duplicates'
  get 'location_duplicates', :to => 'locations#duplicates'
  get 'sector_duplicates', :to => 'sectors#duplicates'
  get 'product_duplicates', :to => 'products#duplicates'
  get 'building_block_duplicates', :to => 'building_blocks#duplicates'
  get 'organization_duplicates', :to => 'organizations#duplicates'
  get 'use_case_duplicates', :to => 'use_cases#duplicates'
  get 'workflow_duplicates', :to => 'workflows#duplicates'
  get 'glossary_duplicates', :to => 'glossaries#duplicates'
  get 'product_suite_duplicates', :to => 'product_suites#duplicates'
  get 'deploys_refresh_list', :to => 'deploys#refresh_list'
  get 'project_duplicates', to: 'projects#duplicates'
  get 'portal_view_duplicates', to: 'portal_views#duplicates'
  get 'use_case_step_duplicates', to: 'use_case_steps#duplicates'
  get 'tag_duplicates', to: 'tags#duplicates'
  get 'category_indicator_duplicates', to: 'category_indicators#duplicates'
  get 'playbook_duplicates', to: 'playbooks#duplicates'
  get 'playbook_page_duplicates', to: 'playbook_pages#duplicates'
  get 'candidate_product_duplicates', to: 'candidate_products#duplicates'

  post '/froala_image/upload' => 'froala_images#upload'

  get 'covidresources', :to => 'covid#resources'
  get 'productlist', :to => 'products#productlist', as: :productlist
  get 'productmap', :to => 'products#map'

  get 'map_projects', to: 'projects#map_projects'
  get 'map_covid', to: 'projects#map_covid'

  get 'map', to: 'organizations#map'
  get 'map_osm', to: 'organizations#map_osm'
  get 'map_fs', :to => 'organizations#map_fs'
  get 'map_aggregators_osm', to: 'organizations#map_aggregators_osm'
  get 'map_projects_osm', to: 'projects#map_projects_osm'
end

app/views/shared/menu/_admin.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle mt-2" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
     aria-haspopup="true" aria-expanded="false">
    <strong><%= t('view.header.admin-data') %></strong>
  </a>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
    <%= link_to t('model.city').to_s.pluralize.titlecase, cities_path, :class => 'dropdown-item' %>
    <%= link_to t('model.contact').to_s.pluralize.titlecase, contacts_path, :class => 'dropdown-item' %>
    <%= link_to t('model.country').to_s.pluralize.titlecase, countries_path, :class => 'dropdown-item' %>
    <%= link_to t('model.project').to_s.pluralize.titlecase, projects_path, :class => 'dropdown-item' %>
    <%= link_to t('model.sector').to_s.pluralize.titlecase, sectors_path, :class => 'dropdown-item' %>
    <%= link_to t('model.tag').to_s.pluralize.titlecase, tags_path, :class => 'dropdown-item' %>
    <%= link_to t('model.user').to_s.pluralize.titlecase, users_path, :class => 'dropdown-item' %>
    <%= link_to t('model.user-event').to_s.pluralize.titlecase, statistics_users_path, :class => 'dropdown-item' %>
    <div class="dropdown-divider"></div>
    <%= link_to t('model.candidate-organization').to_s.pluralize.titlecase, candidate_organizations_path, class: 'dropdown-item' %>
    <%= link_to t('model.candidate-product').to_s.pluralize.titlecase, candidate_products_path, class: 'dropdown-item' %>
    <%= link_to t('model.candidate-role').to_s.pluralize.titlecase, candidate_roles_path, :class => 'dropdown-item' %>
    <% if (policy(current_user).mni?) %>
      <%= link_to t('model.operator_services').to_s.pluralize.titlecase, operator_services_path, :class => 'dropdown-item' %>
    <% end %>
    <%= link_to t('model.product-suite').to_s.pluralize.titlecase, product_suites_path, :class => 'dropdown-item' %>
    <div class="dropdown-divider"></div>
    <%= link_to t('model.deploys').to_s.pluralize.titlecase, deploys_path, :class => 'dropdown-item' %>
    <%= link_to t('model.portal-view').to_s.pluralize.titlecase, portal_views_path, :class => 'dropdown-item' %>
    <%= link_to t('model.maturity-rubric').to_s.pluralize.titlecase, maturity_rubrics_path, :class => 'dropdown-item' %>
  </div>
</li>

app/views/shared/menu/_authenticated.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle-avatar" data-toggle="dropdown" href="#" role="button">
    <div class="avatar-circle">
      <span class="initials">
        <%= current_user.email[0].upcase %>
      </span>
    </div>
  </a>
  <div class="dropdown-menu dropdown-menu-right">
    <%= link_to t('view.header.about'), about_path, :class => 'dropdown-item' %>
    <div class="dropdown-divider"></div>
    <%= link_to t('view.header.profile'), edit_user_registration_path, :class => 'dropdown-item' %>
    <% if !current_user.nil? && !current_user.roles.include?(User.user_roles[:admin]) %>
      <%= link_to t('view.header.elevate-role'), new_candidate_role_path, class: 'dropdown-item' %>
    <% end %>
    <% if (policy(current_user).index?) %>   
      <%= link_to t('model.setting').to_s.pluralize.titlecase, settings_path, :class => 'dropdown-item' %>
    <% end %>
    <% if !available_portals.nil? && available_portals.length > 0 %>
      <div class="dropdown-submenu">
        <a class="dropdown-item dropdown-toggle mt-2" href="#" id="navPortal" role="button" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
          <%= t('view.header.view-selection') %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navPortal">
          <% available_portals.each do |available_portal| %>
            <a class="dropdown-item portal-switcher" style="cursor: pointer;" data-portal="<%= available_portal.id %>">
              <%= available_portal.name %>
              <% if session[:portal]['id'] == available_portal.id %>
                (<%= t('view.header.active-portal') %>)
              <% end %>
            </a>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="dropdown-divider"></div>
    <a target="_blank" rel="noreferrer noopener"
       href="https://docs.osc.dial.community/projects/product-registry/en/latest/"
       class="dropdown-item">
      <%= t('view.header.documentation') %>
    </a>
    <%= link_to t('view.header.feedback'), 'mailto:catalog-support@dial.community',
                target: '_blank', class: 'dropdown-item' %>
    <%= link_to t('view.header.logout'), destroy_user_session_path, method: :delete, :class => 'dropdown-item' %>
  </div>
</li>

app/views/shared/menu/_ict4sdg.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle mt-2" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
    aria-haspopup="true" aria-expanded="false">
    <strong><%= t('view.header.ict4sdg-data') %></strong>
  </a>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
    <%= link_to t('model.project').to_s.pluralize.titlecase, projects_path, :class => 'dropdown-item' %>
    <%= link_to t('model.sector').to_s.pluralize.titlecase, sectors_path, :class => 'dropdown-item' %>
    <div class="dropdown-divider"></div>
    <%= link_to t('model.maturity-rubric').to_s.pluralize.titlecase, maturity_rubrics_path, :class => 'dropdown-item' %>
  </div>
</li>

app/views/shared/menu/_mni.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle mt-2" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
    aria-haspopup="true" aria-expanded="false">
    <strong><%= t('view.header.mni-data') %></strong>
  </a>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
      <%= link_to t('model.operator_services').to_s.pluralize.titlecase, operator_services_path, :class => 'dropdown-item' %>
  </div>
</li>

app/views/shared/menu/_principle.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle mt-2" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
    aria-haspopup="true" aria-expanded="false">
    <strong><%= t('view.header.principle-data') %></strong>
  </a>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
    <%= link_to t('model.city').to_s.pluralize.titlecase, cities_path, :class => 'dropdown-item' %>
    <%= link_to t('model.contact').to_s.pluralize.titlecase, contacts_path, :class => 'dropdown-item' %>
    <%= link_to t('model.country').to_s.pluralize.titlecase, countries_path, :class => 'dropdown-item' %>
    <%= link_to t('model.sector').to_s.pluralize.titlecase, sectors_path, :class => 'dropdown-item' %>
    <%= link_to t('model.organization').to_s.pluralize.titlecase, organizations_path, :class => 'dropdown-item' %>
  </div>
</li>

app/views/shared/menu/_unauthenticated.html.erb
<li class="mt-2">
  <%= link_to t('view.header.about'), about_path,
              class: 'nav-link unauth-item' %>
</li>
<li class="mt-2">
  <%= link_to t('view.header.sign-up'), new_user_registration_path,
              class: 'nav-link unauth-item' %>
</li>
<li class="mt-2">
  <%= link_to t('view.header.login'), new_user_session_path,
              class: 'nav-link unauth-item' %>
</li>
<li class="mt-2">
  <a target="_blank" rel="noreferrer noopener"
     href="https://docs.osc.dial.community/projects/product-registry/en/latest/"
     class="nav-link unauth-item">
    <%= t('view.header.documentation') %>
  </a>
</li>