config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount(GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql")
  end

  post "/graphql", to: "graphql#execute"

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  mount Commontator::Engine => '/commontator'

  resources :task_trackers

  resources :candidate_products do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :candidate_roles do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :product_suites
  resources :glossaries
  resources :settings

  resources :rubric_categories, only: [:index, :update, :create, :destroy]
  resources :category_indicators, only: [:index, :update, :create, :destroy]
  resources :maturity_rubrics do
    resources :rubric_categories do
      resources :category_indicators
    end
  end

  resources :tasks, only: [:index, :update, :create, :destroy]
  resources :activities, only: [:index, :update, :create, :destroy]

  resources :playbook_pages, only: [:index, :update, :create, :destroy]
  resources :playbooks do
    get 'count', on: :collection
    post 'upload_design_images', on: :collection
    member do
      post 'convert_pages'
    end
    resources :playbook_pages do
      member do
        get 'copy_page'
        get 'edit_content'
        get 'load_design'
        post 'save_design'
        patch 'save_design'
        get 'create_pdf'
        get 'show_pdf'
      end
    end
  end

  resources :tags
  resources :use_case_steps

  resources :projects do
    get 'count', on: :collection
    get 'export_data', on: :collection
    member do
      post 'favorite_project'
      post 'unfavorite_project'
    end
  end

  get 'deploys/index'
  get 'about/learnmore'
  get 'about', to: 'about#index'

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  scope '/admin' do
    resources :users do
      get 'statistics', on: :collection
    end
  end

  devise_scope :user do
    get '/users', to: 'registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end

  root to: redirect(path: '/products')

  resources :covid, only: [:index]

  resources :candidate_organizations do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :portal_views do
    member do
      post 'select'
    end
  end

  resources :products do
    get 'count', on: :collection
    get 'export_data', on: :collection
    member do
      post 'favorite_product'
      post 'unfavorite_product'
    end
  end

  resources :building_blocks do
    get 'count', on: :collection
    get 'export_data', on: :collection
  end

  resources :sustainable_development_goals, only: [:index, :show] do
    get 'count', on: :collection
  end

  resources :sdg_targets, only: [:index, :show]

  resources :use_case_steps, only: [:new, :create, :edit, :update, :show]
  resources :use_cases do
    get 'count', on: :collection
    get 'export_data', on: :collection
    resources :use_case_steps, only: [:new, :create, :edit, :update, :show]
    member do
      post 'favorite_use_case'
      post 'unfavorite_use_case'
    end
  end

  resources :workflows do
    get 'count', on: :collection
    get 'export_data', on: :collection
  end

  resources :deploys do
    get 'show_messages'
    post 'add_ssh_user'
  end

  resources :organizations do
    get 'count', on: :collection
    get 'export_data', on: :collection
  end

  get :update_locale, controller:"application"

  # Start of external API routes
  get 'api/v1/organizations/:id', to: 'organizations#unique_search'
  get 'api/v1/organizations', to: 'organizations#simple_search'
  post 'api/v1/organizations', to: 'organizations#complex_search'

  get 'api/v1/building_blocks/:id', to: 'building_blocks#unique_search'
  get 'api/v1/building_blocks', to: 'building_blocks#simple_search'
  post 'api/v1/building_blocks', to: 'building_blocks#complex_search'

  get 'api/v1/cities/:id', to: 'cities#unique_search'
  get 'api/v1/cities', to: 'cities#simple_search'

  get 'api/v1/countries/:id', to: 'countries#unique_search'
  get 'api/v1/countries', to: 'countries#simple_search'

  get 'api/v1/products/:id', to: 'products#unique_search'
  get 'api/v1/products', to: 'products#simple_search'
  post 'api/v1/products', to: 'products#complex_search'

  get 'api/v1/projects/:id', to: 'projects#unique_search'
  get 'api/v1/projects', to: 'projects#simple_search'
  post 'api/v1/projects', to: 'projects#complex_search'

  get 'api/v1/sectors/:id', to: 'sectors#unique_search'
  get 'api/v1/sectors', to: 'sectors#simple_search'

  get 'api/v1/sdgs/:id', to: 'sustainable_development_goals#unique_search'
  get 'api/v1/sdgs', to: 'sustainable_development_goals#simple_search'

  get 'api/v1/sustainable_development_goals/:id', to: 'sustainable_development_goals#unique_search'
  get 'api/v1/sustainable_development_goals', to: 'sustainable_development_goals#simple_search'

  get 'api/v1/tags/:id', to: 'tags#unique_search'
  get 'api/v1/tags', to: 'tags#simple_search'

  get 'api/v1/use_cases/:id', to: 'use_cases#unique_search'
  get 'api/v1/use_cases', to: 'use_cases#simple_search'
  post 'api/v1/use_cases', to: 'use_cases#complex_search'

  get 'api/v1/use_cases/:id/use_case_steps/:step_id', to: 'use_case_steps#unique_search'
  get 'api/v1/use_cases/:id/use_case_steps', to: 'use_case_steps#simple_search'

  get 'api/v1/workflows/:id', to: 'workflows#unique_search'
  get 'api/v1/workflows', to: 'workflows#simple_search'
  post 'api/v1/workflows', to: 'workflows#complex_search'

  # End of external API routes

  resources :operator_services
  resources :audits, only: [:index]
  resources :stylesheets

  resources :cities, only: [:index, :show]
  resources :countries, only: [:index, :show]

  resources :locations do
    resources :organizations
  end

  resources :sectors do
    resources :organizations
    resources :use_cases
  end

  resources :contacts do
    resources :organizations
  end

  resources :tags
  resources :use_case_steps

  get '/object_counts', to: 'application#object_counts', as: :object_counts
  post '/add_filter', to: 'application#add_filter', as: :add_filter
  post '/add_filters', to: 'application#add_filters', as: :add_filters
  post '/remove_filter', to: 'application#remove_filter', as: :remove_filter
  post '/remove_all_filters', to: 'application#remove_all_filters', as: :remove_all_filters
  get '/get_filters', to: 'application#get_filters', as: :get_filters
  get '/agg_capabilities', to: 'organizations#agg_capabilities', as: :agg_capabilities
  get '/agg_services', to: 'organizations#agg_services', as: :agg_services
  get '/service_capabilities', to: 'organizations#service_capabilities', as: :service_capabilities
  get '/update_capability', to: 'organizations#update_capability', as: :update_capability
  get '/privacy', to: 'about#privacy', as: :privacy
  get '/terms', to: 'about#terms', as: :terms
  get '/healthcheck', to: 'about#healthcheck', as: :healthcheck

  post '/save_url', to: 'application#save_url', as: :save_url
  post '/remove_url', to: 'application#remove_url', as: :remove_url

  get 'export', :to => 'organizations#export'
  get 'candidate_organization_duplicates', :to => 'candidate_organizations#duplicates'
  get 'contact_duplicates', :to => 'contacts#duplicates'
  get 'location_duplicates', :to => 'locations#duplicates'
  get 'sector_duplicates', :to => 'sectors#duplicates'
  get 'product_duplicates', :to => 'products#duplicates'
  get 'building_block_duplicates', :to => 'building_blocks#duplicates'
  get 'organization_duplicates', :to => 'organizations#duplicates'
  get 'use_case_duplicates', :to => 'use_cases#duplicates'
  get 'workflow_duplicates', :to => 'workflows#duplicates'
  get 'glossary_duplicates', :to => 'glossaries#duplicates'
  get 'product_suite_duplicates', :to => 'product_suites#duplicates'
  get 'deploys_refresh_list', :to => 'deploys#refresh_list'
  get 'project_duplicates', to: 'projects#duplicates'
  get 'portal_view_duplicates', to: 'portal_views#duplicates'
  get 'use_case_step_duplicates', to: 'use_case_steps#duplicates'
  get 'tag_duplicates', to: 'tags#duplicates'
  get 'category_indicator_duplicates', to: 'category_indicators#duplicates'
  get 'playbook_duplicates', to: 'playbooks#duplicates'
  get 'playbook_page_duplicates', to: 'playbook_pages#duplicates'
  get 'candidate_product_duplicates', to: 'candidate_products#duplicates'

  post '/froala_image/upload' => 'froala_images#upload'

  get 'covidresources', :to => 'covid#resources'
  get 'productlist', :to => 'products#productlist', as: :productlist
  get 'productmap', :to => 'products#map'

  get 'map_projects', to: 'projects#map_projects'
  get 'map_covid', to: 'projects#map_covid'

  get 'map', to: 'organizations#map'
  get 'map_osm', to: 'organizations#map_osm'
  get 'map_fs', :to => 'organizations#map_fs'
  get 'map_aggregators_osm', to: 'organizations#map_aggregators_osm'
  get 'map_projects_osm', to: 'projects#map_projects_osm'
end

app/models/candidate_product.rb
class CandidateProduct < ApplicationRecord
end

app/controllers/candidate_products_controller.rb
class CandidateProductsController < ApplicationController
  before_action :set_candidate_product, only: [:show, :edit, :update, :destroy, :duplicate, :approve, :reject]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :duplicate, :approve, :reject]

  def approve
    set_candidate_product
    authorize(@candidate_product, :mod_allowed?)

    product = Product.new
    product.name = @candidate_product.name
    product.website = @candidate_product.website

    product.slug = @candidate_product.slug

    duplicates = Product.where(slug: product.slug)
    if duplicates.count.positive?
      first_duplicate = Product.slug_starts_with(product.slug).order(slug: :desc).first
      product.slug = product.slug + generate_offset(first_duplicate).to_s
    end

    respond_to do |format|
      # Don't re-approve approved candidate.
      if (@candidate_product.rejected.nil? || @candidate_product.rejected) &&
        product.save && @candidate_product.update(rejected: false, approved_date: Time.now,
                                                  approved_by_id: current_user.id)
        format.html { redirect_to product_url(product), notice: 'Candidate promoted to product.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { redirect_to candidate_products_url, flash: { error: 'Unable to approve candidate.' } }
        format.json { head :no_content }
      end
    end
  end

  def reject
    set_candidate_product
    authorize(@candidate_product, :mod_allowed?)
    respond_to do |format|
      # Can only approve new submission.
      if @candidate_product.rejected.nil? &&
         @candidate_product.update(rejected: true, rejected_date: Time.now, rejected_by_id: current_user.id)
        format.html { redirect_to candidate_products_url, notice: 'Candidate rejected.' }
      else
        format.html { redirect_to candidate_products_url, flash: { error: 'Unable to reject candidate.' } }
      end
      format.json { head :no_content }
    end
  end

  # GET /candidate_products
  # GET /candidate_products.json
  def index
    @candidate_products = CandidateProduct.all
    authorize(@candidate_products, :view_allowed?)
  end

  # GET /candidate_products/1
  # GET /candidate_products/1.json
  def show
    authorize(@candidate_product, :view_allowed?)
  end

  # GET /candidate_products/new
  def new
    @candidate_product = CandidateProduct.new
    authorize(@candidate_product, :create_allowed?)
  end

  # GET /candidate_products/1/edit
  def edit
    authorize(@candidate_product, :mod_allowed?)
  end

  # POST /candidate_products
  # POST /candidate_products.json
  def create
    authorize(CandidateProduct, :create_allowed?)
    @candidate_product = CandidateProduct.new(candidate_product_params)

    respond_to do |format|
      if @candidate_product.save
        format.html { redirect_to @candidate_product, notice: 'Candidate product was successfully created.' }
        format.json { render :show, status: :created, location: @candidate_product }
      else
        format.html { render :new }
        format.json { render json: @candidate_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidate_products/1
  # PATCH/PUT /candidate_products/1.json
  def update
    authorize(@candidate_product, :mod_allowed?)
    respond_to do |format|
      if @candidate_product.update(candidate_product_params)
        format.html { redirect_to @candidate_product, notice: 'Candidate product was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate_product }
      else
        format.html { render :edit }
        format.json { render json: @candidate_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidate_products/1
  # DELETE /candidate_products/1.json
  def destroy
    authorize(@candidate_product, :mod_allowed?)
    @candidate_product.destroy
    respond_to do |format|
      format.html { redirect_to candidate_products_url, notice: 'Candidate product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def duplicates
    @candidate_products = []
    if params[:current].present?
      current_slug = slug_em(params[:current])
      original_slug = slug_em(params[:original])
      if current_slug != original_slug
        @candidate_products = CandidateProduct.where(slug: current_slug)
                                              .select(:name, :slug)
                                              .to_a
      end
    end
    authorize(CandidateProduct, :view_allowed?)
    render(json: @candidate_products, only: [:name])
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_candidate_product
    @candidate_product = CandidateProduct.find_by(slug: params[:id])
    if @candidate_product.nil? && params[:id].scan(/\D/).empty?
      @candidate_product = CandidateProduct.find(params[:id])
    end
  end

  # Only allow a list of trusted parameters through.
  def candidate_product_params
    params.require(:candidate_product)
          .permit(:name, :website, :repository, :submitter_email)
          .tap do |attr|
            if attr[:website].present?
              attr[:website] = attr[:website].strip
                                             .sub(/^https?\:\/\//i, '')
                                             .sub(/^https?\/\/\:/i, '')
                                             .sub(/\/$/, '')
            end
            if params[:reslug].present?
              attr[:slug] = slug_em(attr[:name])
              if params[:duplicate].present?
                first_duplicate = CandidateProduct.slug_starts_with(attr[:slug])
                                                  .order(slug: :desc).first
                attr[:slug] = attr[:slug] + generate_offset(first_duplicate).to_s
              end
            end
          end
  end
end

app/helpers/candidate_products_helper.rb
module CandidateProductsHelper
end

app/views/candidate_products/_form.html.erb
<%= form_with(model: candidate_product, local: true) do |form| %>

  <fieldset class="form-label-group">
    <%= form.text_field :name, id: :candidate_product_name,
                        class: "form-control", placeholder: t('view.general.name') %>
    <%= form.label :name, t('view.general.name') %>
  </fieldset>

  <input id="original_name" type="hidden" value="<%= candidate_product.name %>" />
  <div id="duplicate-warning" class="alert alert-warning">
    <%= t('view.general.duplicates', model: t('model.candidate-product')) %>
  </div>

  <fieldset class="form-label-group">
    <%= form.text_field :website, id: :candidate_product_website,
        class: "form-control", placeholder: t('view.product.form.website') %>
    <%= form.label :website, t('view.product.form.website') %>
  </fieldset>

  <fieldset class="form-label-group">
    <%= form.text_field :repository, id: :candidate_product_repository,
        class: "form-control", placeholder: t('view.product.form.repository') %>
    <%= form.label :repository, t('view.product.form.repository') %>
  </fieldset>

  <fieldset class="form-label-group">
    <%= form.text_field :submitter_email, id: :candidate_product_submitter_email,
        class: "form-control", required: true, placeholder: t('view.product.form.submitter-email') %>
    <%= form.label :submitter_email, t('view.product.form.submitter-email') %>
  </fieldset>

  <fieldset class="float-right mt-4">
    <%= form.submit t('view.general.submit'), id: 'submit-candidate', class: "btn btn-primary",
                    disabled: !(candidate_product.rejected.nil? || candidate_product.rejected) %>
    <%= link_to t('view.general.back'), "javascript:window.history.back()", class: 'btn btn-outline-secondary' %>
  </fieldset>
<% end %>

app/views/candidate_products/edit.html.erb
<% if @candidate_product.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t('view.general.error', count: @candidate_product.errors.count) %>
    </div>
  </div>
<% end %>
<div class="border rounded bg-secondary text-white p-3">
  <%= t('view.general.title.edit', model: t('model.candidate-product')) %>
</div>
<%= render 'form', candidate_product: @candidate_product %>

app/views/candidate_products/index.html.erb
<p class="text-success"><%= flash[:notice] %></p>
<p class="text-danger"><%= flash[:error] %></p>

<% if user_signed_in? %>
  <%= link_to new_candidate_product_path, class: 'btn btn-outline-secondary float-left ml-1' do %>
    <span class="d-none d-md-block"><%= t('view.general.create') %></span>
    <span class="d-block d-md-none">
      <i class="fa fa-plus fa-sm" aria-hidden="true"></i>
    </span>
  <% end %>
<% end %>
<div class="float-right pb-2">
  <%= form_tag(candidate_products_path, :method => "get", id: "search-form", class: "form-inline") do %>
    <%= text_field_tag :search, params[:search],
        placeholder: t('view.general.search-placeholder', model: t('model.candidate-product').to_s.pluralize),
        class: "form-control" %>
    <div class="input-group-append">
      <%= submit_tag t('view.general.search'), :class => "btn btn-secondary" %>
    </div>
  <% end %>
</div>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th class="d-none d-md-table-cell">
        <%= t('view.general.name') %>
      </th>
      <th class="d-none d-md-table-cell">
        <%= t('view.candidate-product.index.website') %>
      </th>
      <th class="d-none d-md-table-cell">
        <%= t('view.candidate-product.index.status') %>
      </th>
      <th class="d-table-cell d-md-none">
        <%= t('model.candidate-product').titlecase %>
      </th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% if @candidate_products.count > 0 %>
      <% @candidate_products.each do |candidate_product| %>
        <tr>
          <td class="d-none d-md-table-cell"><%= candidate_product.name %></td>
          <td class="d-none d-md-table-cell"><%= candidate_product.website %></td>
          <td class="d-none d-md-table-cell">
            <%= candidate_product.rejected.nil? ?
                t('view.candidate-product.index.status-new') :
                candidate_product.rejected ?
                  t('view.candidate-product.index.status-rejected') :
                  t('view.candidate-product.index.status-approved')
            %>
          </td>
          <td class="d-table-cell d-md-none">
            <%= candidate_product.name %>
            <div class="text-muted">
              <%= candidate_product.website %>
            </div>
            <div class="text-muted">
              <%= candidate_product.rejected.nil? ?
                  t('view.candidate-product.index.status-new') :
                  candidate_product.rejected ?
                    t('view.candidate-product.index.status-rejected') :
                    t('view.candidate-product.index.status-approved')
              %>
            </div>
          </td>
          <td class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
               aria-haspopup="true" aria-expanded="false">
              <%= t('view.general.action') %>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <%= link_to t('view.general.view'), candidate_product, :class =>"dropdown-item"  %>
              <% if user_signed_in? && policy(candidate_product).mod_allowed? %>
                <% if candidate_product.rejected.nil? || candidate_product.rejected %>
                  <%= link_to t('view.general.edit'), edit_candidate_product_path(candidate_product), :class =>"dropdown-item"  %>
                <% end %>
                <div class="dropdown-divider"></div>
                <% if candidate_product.rejected.nil? %>
                  <%= link_to t('view.candidate-product.index.approve'),
                              approve_candidate_product_path(candidate_product),
                              method: :post, :class =>"dropdown-item"  %>
                  <%= link_to t('view.candidate-product.index.reject'),
                              reject_candidate_product_path(candidate_product),
                              method: :post, :class =>"dropdown-item"  %>
                  <div class="dropdown-divider"></div>
                <% end %>
                <% if candidate_product.rejected %>
                  <%= link_to t('view.candidate-product.index.approve'),
                              approve_candidate_product_path(candidate_product),
                              method: :post, :class =>"dropdown-item"  %>
                  <div class="dropdown-divider"></div>
                <% end %>
                <%= link_to t('view.general.delete'), candidate_product, method: :delete,
                            data: { confirm: t('view.general.delete-confirmation', model: t('model.candidate-product')) },
                            class: "dropdown-item" %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="5">
          <small class="text-muted"><%= t('view.candidate-product.index.no-data') %></small>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/candidate_products/new.html.erb
<% if @candidate_product.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t('view.general.error', count: @candidate_product.errors.count) %>
    </div>
  </div>
<% end %>
<div class="border rounded bg-secondary text-white p-3">
  <%= t('view.general.title.create', model: t('model.candidate-product')) %>
</div>
<%= render 'form', candidate_product: @candidate_product %>

app/views/candidate_products/show.html.erb
<p class="text-success"><%= flash[:notice] %></p>
<p class="text-danger"><%= flash[:error] %></p>

<div class="row">
  <div class="col-8 mb-2">
    <% if user_signed_in? && policy(@candidate_product).mod_allowed? %>
      <%= link_to t('view.general.delete-with-model', model: t('model.candidate-product').titlecase),
                  @candidate_product, method: :delete,
                  data: { confirm: t('view.general.delete-confirmation', model: t('model.candidate-product')) },
                  class: 'btn btn-outline-secondary float-left ml-1' %>
    <% end %>
  </div>
</div>
<div class="rounded bg-secondary text-white card-header">
  <%= "#{t('model.candidate-product').titlecase}:  #{@candidate_product.name}" %>
</div>

<div class="mt-2">
  <div class="row">
    <div class="col-lg-8 col-12">
      <p class="m-2">
        <strong><%= "#{t('view.candidate-product.index.website')}:" %></strong>
        <%= link_to @candidate_product.website.downcase.strip, "//#{@candidate_product.website.downcase.strip}", target: :_blank %>
      </p>
      <p class="m-2">
        <strong><%= "#{t('view.candidate-product.index.status')}:" %></strong>
        <%= @candidate_product.rejected.nil? ?
            t('view.candidate-product.index.status-new') :
            @candidate_product.rejected ?
              t('view.candidate-product.index.status-rejected') :
              t('view.candidate-product.index.status-approved')
        %>
      </p>
      <% if user_signed_in? && policy(Contact).view_allowed? %>
        <p class="m-2">
          <strong><%= "#{t('view.candidate-product.index.submitter-email')}:" %></strong>
          <%= @candidate_product.submitter_email %>
        </p>
      <% end %>
    </div>
  </div>
  <p class="float-right mb-0 mr-2" >
    <% if user_signed_in? && policy(@candidate_product).mod_allowed? %>
      <%= link_to t('view.general.back'), candidate_products_path, class: "card-link" %>
      <%= link_to t('view.general.edit'), edit_candidate_product_path(@candidate_product), class: "card-link" %>
    <% end %>
  </p>
</div>