config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount(GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql")
  end

  post "/graphql", to: "graphql#execute"

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  mount Commontator::Engine => '/commontator'

  resources :task_trackers

  resources :candidate_products do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :candidate_roles do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :product_suites
  resources :glossaries
  resources :settings

  resources :rubric_categories, only: [:index, :update, :create, :destroy]
  resources :category_indicators, only: [:index, :update, :create, :destroy]
  resources :maturity_rubrics do
    resources :rubric_categories do
      resources :category_indicators
    end
  end

  resources :tasks, only: [:index, :update, :create, :destroy]
  resources :activities, only: [:index, :update, :create, :destroy]

  resources :playbook_pages, only: [:index, :update, :create, :destroy]
  resources :playbooks do
    get 'count', on: :collection
    post 'upload_design_images', on: :collection
    member do
      post 'convert_pages'
    end
    resources :playbook_pages do
      member do
        get 'copy_page'
        get 'edit_content'
        get 'load_design'
        post 'save_design'
        patch 'save_design'
        get 'create_pdf'
        get 'show_pdf'
      end
    end
  end

  resources :tags
  resources :use_case_steps

  resources :projects do
    get 'count', on: :collection
    get 'export_data', on: :collection
    member do
      post 'favorite_project'
      post 'unfavorite_project'
    end
  end

  get 'deploys/index'
  get 'about/learnmore'
  get 'about', to: 'about#index'

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  scope '/admin' do
    resources :users do
      get 'statistics', on: :collection
    end
  end

  devise_scope :user do
    get '/users', to: 'registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end

  root to: redirect(path: '/products')

  resources :covid, only: [:index]

  resources :candidate_organizations do
    member do
      post 'reject'
      post 'approve'
    end
  end

  resources :portal_views do
    member do
      post 'select'
    end
  end

  resources :products do
    get 'count', on: :collection
    get 'export_data', on: :collection
    member do
      post 'favorite_product'
      post 'unfavorite_product'
    end
  end

  resources :building_blocks do
    get 'count', on: :collection
    get 'export_data', on: :collection
  end

  resources :sustainable_development_goals, only: [:index, :show] do
    get 'count', on: :collection
  end

  resources :sdg_targets, only: [:index, :show]

  resources :use_case_steps, only: [:new, :create, :edit, :update, :show]
  resources :use_cases do
    get 'count', on: :collection
    get 'export_data', on: :collection
    resources :use_case_steps, only: [:new, :create, :edit, :update, :show]
    member do
      post 'favorite_use_case'
      post 'unfavorite_use_case'
    end
  end

  resources :workflows do
    get 'count', on: :collection
    get 'export_data', on: :collection
  end

  resources :deploys do
    get 'show_messages'
    post 'add_ssh_user'
  end

  resources :organizations do
    get 'count', on: :collection
    get 'export_data', on: :collection
  end

  get :update_locale, controller:"application"

  # Start of external API routes
  get 'api/v1/organizations/:id', to: 'organizations#unique_search'
  get 'api/v1/organizations', to: 'organizations#simple_search'
  post 'api/v1/organizations', to: 'organizations#complex_search'

  get 'api/v1/building_blocks/:id', to: 'building_blocks#unique_search'
  get 'api/v1/building_blocks', to: 'building_blocks#simple_search'
  post 'api/v1/building_blocks', to: 'building_blocks#complex_search'

  get 'api/v1/cities/:id', to: 'cities#unique_search'
  get 'api/v1/cities', to: 'cities#simple_search'

  get 'api/v1/countries/:id', to: 'countries#unique_search'
  get 'api/v1/countries', to: 'countries#simple_search'

  get 'api/v1/products/:id', to: 'products#unique_search'
  get 'api/v1/products', to: 'products#simple_search'
  post 'api/v1/products', to: 'products#complex_search'

  get 'api/v1/projects/:id', to: 'projects#unique_search'
  get 'api/v1/projects', to: 'projects#simple_search'
  post 'api/v1/projects', to: 'projects#complex_search'

  get 'api/v1/sectors/:id', to: 'sectors#unique_search'
  get 'api/v1/sectors', to: 'sectors#simple_search'

  get 'api/v1/sdgs/:id', to: 'sustainable_development_goals#unique_search'
  get 'api/v1/sdgs', to: 'sustainable_development_goals#simple_search'

  get 'api/v1/sustainable_development_goals/:id', to: 'sustainable_development_goals#unique_search'
  get 'api/v1/sustainable_development_goals', to: 'sustainable_development_goals#simple_search'

  get 'api/v1/tags/:id', to: 'tags#unique_search'
  get 'api/v1/tags', to: 'tags#simple_search'

  get 'api/v1/use_cases/:id', to: 'use_cases#unique_search'
  get 'api/v1/use_cases', to: 'use_cases#simple_search'
  post 'api/v1/use_cases', to: 'use_cases#complex_search'

  get 'api/v1/use_cases/:id/use_case_steps/:step_id', to: 'use_case_steps#unique_search'
  get 'api/v1/use_cases/:id/use_case_steps', to: 'use_case_steps#simple_search'

  get 'api/v1/workflows/:id', to: 'workflows#unique_search'
  get 'api/v1/workflows', to: 'workflows#simple_search'
  post 'api/v1/workflows', to: 'workflows#complex_search'

  # End of external API routes

  resources :operator_services
  resources :audits, only: [:index]
  resources :stylesheets

  resources :cities, only: [:index, :show]
  resources :countries, only: [:index, :show]

  resources :locations do
    resources :organizations
  end

  resources :sectors do
    resources :organizations
    resources :use_cases
  end

  resources :contacts do
    resources :organizations
  end

  resources :tags
  resources :use_case_steps

  get '/object_counts', to: 'application#object_counts', as: :object_counts
  post '/add_filter', to: 'application#add_filter', as: :add_filter
  post '/add_filters', to: 'application#add_filters', as: :add_filters
  post '/remove_filter', to: 'application#remove_filter', as: :remove_filter
  post '/remove_all_filters', to: 'application#remove_all_filters', as: :remove_all_filters
  get '/get_filters', to: 'application#get_filters', as: :get_filters
  get '/agg_capabilities', to: 'organizations#agg_capabilities', as: :agg_capabilities
  get '/agg_services', to: 'organizations#agg_services', as: :agg_services
  get '/service_capabilities', to: 'organizations#service_capabilities', as: :service_capabilities
  get '/update_capability', to: 'organizations#update_capability', as: :update_capability
  get '/privacy', to: 'about#privacy', as: :privacy
  get '/terms', to: 'about#terms', as: :terms
  get '/healthcheck', to: 'about#healthcheck', as: :healthcheck

  post '/save_url', to: 'application#save_url', as: :save_url
  post '/remove_url', to: 'application#remove_url', as: :remove_url

  get 'export', :to => 'organizations#export'
  get 'candidate_organization_duplicates', :to => 'candidate_organizations#duplicates'
  get 'contact_duplicates', :to => 'contacts#duplicates'
  get 'location_duplicates', :to => 'locations#duplicates'
  get 'sector_duplicates', :to => 'sectors#duplicates'
  get 'product_duplicates', :to => 'products#duplicates'
  get 'building_block_duplicates', :to => 'building_blocks#duplicates'
  get 'organization_duplicates', :to => 'organizations#duplicates'
  get 'use_case_duplicates', :to => 'use_cases#duplicates'
  get 'workflow_duplicates', :to => 'workflows#duplicates'
  get 'glossary_duplicates', :to => 'glossaries#duplicates'
  get 'product_suite_duplicates', :to => 'product_suites#duplicates'
  get 'deploys_refresh_list', :to => 'deploys#refresh_list'
  get 'project_duplicates', to: 'projects#duplicates'
  get 'portal_view_duplicates', to: 'portal_views#duplicates'
  get 'use_case_step_duplicates', to: 'use_case_steps#duplicates'
  get 'tag_duplicates', to: 'tags#duplicates'
  get 'category_indicator_duplicates', to: 'category_indicators#duplicates'
  get 'playbook_duplicates', to: 'playbooks#duplicates'
  get 'playbook_page_duplicates', to: 'playbook_pages#duplicates'
  get 'candidate_product_duplicates', to: 'candidate_products#duplicates'

  post '/froala_image/upload' => 'froala_images#upload'

  get 'covidresources', :to => 'covid#resources'
  get 'productlist', :to => 'products#productlist', as: :productlist
  get 'productmap', :to => 'products#map'

  get 'map_projects', to: 'projects#map_projects'
  get 'map_covid', to: 'projects#map_covid'

  get 'map', to: 'organizations#map'
  get 'map_osm', to: 'organizations#map_osm'
  get 'map_fs', :to => 'organizations#map_fs'
  get 'map_aggregators_osm', to: 'organizations#map_aggregators_osm'
  get 'map_projects_osm', to: 'projects#map_projects_osm'
end

app/controllers/portal_views_controller.rb
class PortalViewsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_portal_view, only: [:show, :edit, :update, :destroy]

  # GET /portal_views
  # GET /portal_views.json
  def index
    if params[:search]
      @portal_views = PortalView.where(nil)
                                .name_contains(params[:search])
                                .order(:name)
                                .paginate(page: params[:page], per_page: 20)
    else
      @portal_views = PortalView.order(:name)
                                .paginate(page: params[:page], per_page: 20)
    end
    authorize @portal_views, :view_allowed?
  end

  def select
    return if current_user.nil?

    authorize PortalView, :view_allowed?

    # Default to the first portal object.
    if session[:portal].nil?
      PortalView.all.each do |portal|
        unless (portal.user_roles & current_user.roles).empty?
          @portal_view = portal
          break
        end
      end
    end

    if !params[:id].nil?
      @portal_view = PortalView.find(params[:id])
      if !@portal_view.nil? && (@portal_view.user_roles & current_user.roles).empty?
        @portal_view = nil
      end
    end
    session[:portal] = @portal_view
    render json: { portal_view: @portal_view }
  end

  # GET /portal_views/1
  # GET /portal_views/1.json
  def show

    stylesheet = Stylesheet.where(portal: @portal_view.slug).first
    if stylesheet.nil?
      stylesheet = Stylesheet.new
    end
    @about_page = stylesheet.about_page
    @stylesheet_color = stylesheet.background_color
    @footer = stylesheet.footer_content
    authorize @portal_view, :view_allowed?
  end

  # GET /portal_views/new
  def new
    @portal_view = PortalView.new
    authorize @portal_view, :view_allowed?
  end

  # GET /portal_views/1/edit
  def edit
    stylesheet = Stylesheet.where(portal: @portal_view.slug).first
    if stylesheet.nil?
      stylesheet = Stylesheet.new
    end
    @about_page = stylesheet.about_page
    @stylesheet_color = stylesheet.background_color
    @footer = stylesheet.footer_content
    authorize @portal_view, :view_allowed?
  end

  # POST /portal_views
  # POST /portal_views.json
  def create
    authorize PortalView, :view_allowed?
    @portal_view = PortalView.new(portal_view_params.except(:about_page, :page_footer))

    respond_to do |format|
      if @portal_view.save
        if params[:logo].present?
          uploader = LogoUploader.new(@portal_view, params[:logo].original_filename, current_user)
          begin
            uploader.store!(params[:logo])
          rescue StandardError => e
            @portal_view.errors.add(:logo, t('errors.messages.extension_whitelist_error'))
          end
        end

        if portal_view_params[:about_page].present?
          stylesheet = Stylesheet.new
          stylesheet.portal = @portal_view.slug
          stylesheet.about_page = portal_view_params[:about_page]
          stylesheet.background_color = portal_view_params[:stylesheet_color]
          stylesheet.footer_content = portal_view_params[:page_footer]
          stylesheet.header_logo = @portal_view.slug+".png"
          stylesheet.save
        end
        format.html { redirect_to @portal_view, notice: 'Portal view was successfully created.' }
        format.json { render :show, status: :created, location: @portal_view }
      else
        format.html { render :new }
        format.json { render json: @portal_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portal_views/1
  # PATCH/PUT /portal_views/1.json
  def update
    if params[:logo].present?
      uploader = LogoUploader.new(@portal_view, params[:logo].original_filename, current_user)
      begin
        uploader.store!(params[:logo])
      rescue StandardError => e
        @portal_view.errors.add(:logo, t('errors.messages.extension_whitelist_error'))
      end
    end

    authorize @portal_view, :view_allowed?
    if portal_view_params[:about_page].present?
      stylesheet = Stylesheet.where(portal: @portal_view.slug).first || Stylesheet.new
      if stylesheet.portal.nil?
        stylesheet.portal = slug_em(portal_view_params[:name])
      end
      stylesheet.about_page = portal_view_params[:about_page]
      stylesheet.background_color = params[:stylesheet_color]
      stylesheet.footer_content = portal_view_params[:page_footer]
      stylesheet.header_logo = @portal_view.slug+".png"
      stylesheet.save
    end

    respond_to do |format|
      if @portal_view.update(portal_view_params.except(:about_page, :page_footer))
        # Update the session's portal if we're editing active portal.
        if session[:portal]['id'] == @portal_view.id
          session[:portal] = @portal_view
        end
        format.html { redirect_to @portal_view, notice: 'Portal view was successfully updated.' }
        format.json { render :show, status: :ok, location: @portal_view }
      else
        format.html { render :edit }
        format.json { render json: @portal_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portal_views/1
  # DELETE /portal_views/1.json
  def destroy
    authorize @portal_view, :view_allowed?
    stylesheet = Stylesheet.where(portal: @portal_view.slug).first
    !stylesheet.nil? && stylesheet.destroy
    @portal_view.destroy
    respond_to do |format|
      format.html { redirect_to portal_views_url, notice: 'Portal view was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def duplicates
    @portal_views = []
    if params[:current].present?
      current_slug = slug_em(params[:current])
      original_slug = slug_em(params[:original])
      if current_slug != original_slug
        @portal_views = PortalView.where(slug: current_slug).to_a
      end
    end

    authorize @portal_views, :view_allowed?
    render json: @portal_views, only: [:name]
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_portal_view
    @portal_view = PortalView.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def portal_view_params
    params.require(:portal_view)
          .permit(:name, :description, :subdomain, :top_nav, :filter_nav, :user_roles, :product_view, :organization_view, :about_page, :page_footer)
          .tap do |attr|
            if params[:selected_top_navs].present?
              attr[:top_navs] =
                params[:selected_top_navs].keys
                                          .map { |key| key }
                                          .reject(&:empty?)
            else
              attr[:top_navs] = []
            end
            if params[:selected_filter_navs].present?
              attr[:filter_navs] =
                params[:selected_filter_navs].keys
                                             .map { |key| key }
                                             .reject(&:empty?)
            else
              attr[:filter_navs] = []
            end
            if params[:selected_user_roles].present?
              attr[:user_roles] =
                params[:selected_user_roles].keys
                                            .map { |key| key }
                                            .reject(&:empty?)
            else
              attr[:user_roles] = []
            end
            if params[:selected_organizations].present?
              attr[:organization_views] =
                params[:selected_organizations].keys
                                               .map { |key| key }
                                               .reject(&:empty?)
            else
              attr[:organization_views] = []
            end
            if params[:selected_products].present?
              attr[:product_views] =
                params[:selected_products].keys
                                          .map { |key| key }
                                          .reject(&:empty?)
            else
              attr[:product_views] = []
            end
            if params[:reslug].present?
              attr[:slug] = slug_em(attr[:name])
              if params[:duplicate].present?
                first_duplicate = PortalView.slug_starts_with(attr[:slug]).order(slug: :desc).first
                attr[:slug] = attr[:slug] + generate_offset(first_duplicate).to_s
              end
            end
          end
  end
end

app/helpers/portal_views_helper.rb
module PortalViewsHelper
end

app/views/portal_views/edit.html.erb
<% if @portal_view.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t('view.general.error', count: @portal_view.errors.count) %>
    </div>
  </div>
<% end %>
<div class="border rounded bg-secondary text-white p-3">
  <%= t('view.general.title.edit', model: t('model.portal-view')) %>
</div>
<%= render 'form', portal_view: @portal_view %>

app/views/portal_views/index.html.erb
<p class="text-success"><%= flash[:notice] %></p>
<p class="text-danger"><%= flash[:error] %></p>

<% if user_signed_in? && policy(PortalView).mod_allowed? %>
  <%= link_to new_portal_view_path, class: 'btn btn-outline-secondary float-left ml-1' do %>
    <span class="d-none d-md-block"><%= t('view.general.create') %></span>
    <span class="d-block d-md-none">
      <i class="fa fa-plus fa-sm" aria-hidden="true"></i>
    </span>
  <% end %>
<% end %>
<div class="form-group float-right mb-2">
  <%= form_tag(portal_views_path, method: "get", id: "search-form", class: "form-inline") do %>
    <%= text_field_tag :search, params[:search], class: "form-control",
        placeholder: t('view.general.search-placeholder', model: t('model.portal-view').to_s.pluralize) %>
    <div class="input-group-append">
      <%= submit_tag t('view.general.search'), class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th class="d-none d-md-table-cell"><%= t('view.general.name') %></th>
      <th class="d-none d-md-table-cell"><%= t('view.general.description') %></th>
      <th class="d-none d-md-table-cell"><%= t('view.filternav.top-nav') %></th>
      <th class="d-none d-md-table-cell"><%= t('view.filternav.filter-nav') %></th>
      <th class="d-none d-md-table-cell"><%= t('view.filternav.user-role') %></th>
      <th class="d-table-cell d-md-none"><%= t('model.portal-view').titlecase %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @portal_views.count > 0 %>
      <% @portal_views.each do |portal_view| %>
        <tr>
          <td class="d-none d-md-table-cell"><%= portal_view.name %></td>
          <td class="d-none d-md-table-cell"><%= portal_view.description %></td>
          <td class="d-none d-md-table-cell">
            <%= portal_view.top_navs
                           .map { |key| I18n.translate("view.filternav.#{key}") }
                           .join(', ') %>
          </td>
          <td class="d-none d-md-table-cell">
            <%= portal_view.filter_navs
                           .map{ |key| I18n.translate("view.filternav.#{key}") }
                           .join(', ') %>
          </td>
          <td class="d-none d-md-table-cell">
            <%= portal_view.user_roles
                           .map{ |key| I18n.translate("view.user.role.#{key}") }
                           .join(', ') %>
          </td>
          <td class="d-table-cell d-md-none">
            <strong><%= portal_view.name %></strong>
            <div class="text-muted">
              <%= portal_view.description %>
            </div>
            <div class="text-muted">
              <span class="font-weight-bold"><%= t('view.filternav.top-nav') %>:</span>
              <%= portal_view.top_navs
                             .map { |key| I18n.translate("view.filternav.#{key}") }
                             .join(', ') %>.
            </div>
            <div class="text-muted">
              <span class="font-weight-bold"><%= t('view.filternav.top-nav') %>:</span>
              <%= portal_view.filter_navs
                             .map{ |key| I18n.translate("view.filternav.#{key}") }
                             .join(', ') %>.
            </div>
            <div class="text-muted">
              <span class="font-weight-bold"><%= t('view.filternav.user-role') %>:</span>
              <%= portal_view.user_roles
                             .map{ |key| I18n.translate("view.user.role.#{key}") }
                             .join(', ') %>.
            </div>
          </td>
          <td class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
               aria-haspopup="true" aria-expanded="false" style="padding-top: 0;">
               <%= t('view.general.action') %>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <%= link_to t('view.general.view'), portal_view, :class =>"dropdown-item" %>
              <% if user_signed_in? && policy(portal_view).mod_allowed? %>
                <%= link_to t('view.general.edit'), edit_portal_view_path(portal_view), :class =>"dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to t('view.general.delete'), portal_view, method: :delete,
                    data: { confirm: t('view.general.delete-confirmation', model: t('model.portal-view')) },
                    class: "dropdown-item" %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="4">
          <small class="text-muted"><%= t('view.portal_view.index.no-data') %></small>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @portal_views, class: 'float-right digg-pagination', inner_window: 1 %>

app/views/portal_views/new.html.erb
<% if @portal_view.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t('view.general.error', count: @portal_view.errors.count) %>
    </div>
  </div>
<% end %>
<div class="border rounded bg-secondary text-white p-3">
  <%= t('view.general.title.create', model: t('model.portal-view')) %>
</div>
<%= render 'form', portal_view: @portal_view %>

app/views/portal_views/show.html.erb
<p class="text-success"><%= flash[:notice] %></p>
<p class="text-danger"><%= flash[:error] %></p>
<div class="card">
  <div class="card-header bg-secondary text-white">
    <%= "#{t('model.portal-view').to_s.titlecase}: #{@portal_view.name}" %>
  </div>
  <div class="card-body py-2">
    <div class="card-text text-muted mt-2 mb-2">
      <strong><%= t('view.general.description') %>:</strong>
      <%= @portal_view.description %> 
    </div>
    <div class="card-text text-muted mt-2 mb-2">
      <strong><%= t('view.portal.form.subdomain') %>:</strong>
      <%= @portal_view.subdomain %> 
    </div>
    <div class="float-right" >
      <%= link_to t('view.general.back'), portal_views_path, :class => "card-link" %>
      <% if user_signed_in? && policy(@portal_view).mod_allowed? %>
        <%= link_to t('view.general.edit'), edit_portal_view_path(@portal_view), :class => "card-link" %>
      <% end %>
    </div>
  </div>
</div>

<div class="mt-4">
  <div class="rounded bg-secondary text-white card-header">
    <%= t('view.portal-view.top-nav').to_s.pluralize.titlecase %>
  </div>
  <% if @portal_view.top_navs.count > 0 %>
    <div class="row">
      <% @portal_view.top_navs.each do |top_nav| %>
        <div class="col-6 col-lg-4 mt-2">
          <div class="card h-100">
            <div class="card-body p-2">
              <div class="m-0"><%= I18n.translate("view.filternav.#{top_nav}") %></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="card-text text-muted">
      <%= t('view.general.not-available', model: t('model.portal-view'), multi: t('view.portal-view.top-nav').to_s.pluralize) %>
    </p>
  <% end %>
</div>

<div class="mt-4">
  <div class="rounded bg-secondary text-white card-header">
    <%= t('view.portal-view.filter-nav').to_s.pluralize.titlecase %>
  </div>
  <% if @portal_view.filter_navs.count > 0 %>
    <div class="row">
      <% @portal_view.filter_navs.each do |filter_nav| %>
        <div class="col-6 col-lg-4 mt-2">
          <div class="card h-100">
            <div class="card-body p-2">
              <div class="m-0"><%= I18n.translate("view.filternav.#{filter_nav}") %></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="card-text text-muted">
      <%= t('view.general.not-available', model: t('model.portal-view'), multi: t('view.portal-view.filter-nav').to_s.pluralize) %>
    </p>
  <% end %>
</div>

<div class="mt-4">
  <div class="rounded bg-secondary text-white card-header">
    <%= t('view.portal-view.user-role').to_s.pluralize.titlecase %>
  </div>
  <% if @portal_view.user_roles.count > 0 %>
    <div class="row">
      <% @portal_view.user_roles.each do |user_role| %>
        <div class="col-6 col-lg-4 mt-2">
          <div class="card h-100">
            <div class="card-body p-2">
              <div class="m-0"><%= I18n.translate("view.user.role.#{user_role}") %></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="card-text text-muted">
      <%= t('view.general.not-available', model: t('model.portal-view'), multi: t('view.portal-view.filter-nav').to_s.pluralize) %>
    </p>
  <% end %>
</div>

<div class="mt-4">
  <div class="rounded bg-secondary text-white card-header">
    <%= t('model.product').to_s.pluralize.titlecase %>
  </div>
  <% if @portal_view.product_views.count > 0 %>
    <div class="row">
      <% @portal_view.product_views.each do |origin| %>
        <div class="col-6 col-lg-4 mt-2">
          <div class="card h-100">
            <div class="card-body p-2">
              <div class="m-0"><%= origin %></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="card-text text-muted">
      <%= t('view.general.not-available', model: t('model.portal-view'), multi: t('model.product').to_s.pluralize) %>
    </p>
  <% end %>
</div>

<div class="mt-4">
  <div class="rounded bg-secondary text-white card-header">
    <%= t('model.organization').to_s.pluralize.titlecase %>
  </div>
  <% if @portal_view.organization_views.count > 0 %>
    <div class="row">
      <% @portal_view.organization_views.each do |org_type| %>
        <div class="col-6 col-lg-4 mt-2">
          <div class="card h-100">
            <div class="card-body p-2">
              <div class="m-0"><%= org_type %></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="card-text text-muted">
      <%= t('view.general.not-available', model: t('model.portal-view'), multi: t('model.organization').to_s.pluralize) %>
    </p>
  <% end %>
</div>

<div class="mt-4">
  <div class="rounded bg-secondary text-white card-header">
    <%= t('view.portal.index.landing-page') %>
  </div>
  <p class="m-2">
    <div id="about-page" class="wysiwyg-viewer">
        <%= @about_page.html_safe %>
    </div>
  </p>
</div>

<div class="mt-4">
  <div class="rounded bg-secondary text-white card-header">
    <%= t('view.portal.index.background-color') %>
  </div>
  <p class="m-2">
    <div class="ml-3"><%= @stylesheet_color %></div>
  </p>
</div>

<div class="mt-4">
  <div class="rounded bg-secondary text-white card-header">
    <%= t('view.portal.index.page-footer') %>
  </div>
  <p class="m-2">
    <div id="page-footer" class="wysiwyg-viewer">
        <%= @footer.html_safe %>
    </div>
  </p>
</div>

<div class="mt-4">
  <div class="rounded bg-secondary text-white card-header">
    <%= t('view.portal.index.header-logo') %>
  </div>
  <%= image_tag "/assets/portal_views/"+ @portal_view.slug + ".png",
                alt: "DIAL Logo", height: "86px", style: "background-color: #ccc" %>
</div>